
BASE_DIR=/home/YVANJ/lua400

all: ilelua

library:
	system "crtlib lua"
	system "crtsrcpf file(lua/luasrc) rcdlen(240)"

ilelua:
	system "crtcmod module(lua/lapi) srcstmf('${BASE_DIR}/src/lapi.c')"
	system "crtcmod module(lua/lauxlib) srcstmf('${BASE_DIR}/src/lauxlib.c')"
	system "crtcmod module(lua/lbaselib) srcstmf('${BASE_DIR}/src/lbaselib.c')"
	system "crtcmod module(lua/lbitlib) srcstmf('${BASE_DIR}/src/lbitlib.c')"
	system "crtcmod module(lua/lcode) srcstmf('${BASE_DIR}/src/lcode.c')"
	system "crtcmod module(lua/lcorolib) srcstmf('${BASE_DIR}/src/lcorolib.c')"
	system "crtcmod module(lua/lctype) srcstmf('${BASE_DIR}/src/lctype.c')"
	system "crtcmod module(lua/ldblib) srcstmf('${BASE_DIR}/src/ldblib.c')"
	system "crtcmod module(lua/ldebug) srcstmf('${BASE_DIR}/src/ldebug.c')"
	system "crtcmod module(lua/ldo) srcstmf('${BASE_DIR}/src/ldo.c')"
	system "crtcmod module(lua/ldump) srcstmf('${BASE_DIR}/src/ldump.c')"
	system "crtcmod module(lua/lfunc) srcstmf('${BASE_DIR}/src/lfunc.c')"
	system "crtcmod module(lua/lgc) srcstmf('${BASE_DIR}/src/lgc.c')"
	system "crtcmod module(lua/linit) srcstmf('${BASE_DIR}/src/linit.c')"
	system "crtcmod module(lua/liolib) srcstmf('${BASE_DIR}/src/liolib.c')"
	system "crtcmod module(lua/llex) srcstmf('${BASE_DIR}/src/llex.c')"
	system "crtcmod module(lua/lmathlib) srcstmf('${BASE_DIR}/src/lmathlib.c')"
	system "crtcmod module(lua/lmem) srcstmf('${BASE_DIR}/src/lmem.c')"
	system "crtcmod module(lua/lmidrange) srcstmf('${BASE_DIR}/src/lmidrangelib.c')"
	system "crtcmod module(lua/loadlib) srcstmf('${BASE_DIR}/src/loadlib.c')"
	system "crtcmod module(lua/lobject) srcstmf('${BASE_DIR}/src/lobject.c')"
	system "crtcmod module(lua/lopcodes) srcstmf('${BASE_DIR}/src/lopcodes.c')"
	system "crtcmod module(lua/loslib) srcstmf('${BASE_DIR}/src/loslib.c')"
	system "crtcmod module(lua/lparser) srcstmf('${BASE_DIR}/src/lparser.c')"
	system "crtcmod module(lua/lstate) srcstmf('${BASE_DIR}/src/lstate.c')"
	system "crtcmod module(lua/lstring) srcstmf('${BASE_DIR}/src/lstring.c')"
	system "crtcmod module(lua/lstrlib) srcstmf('${BASE_DIR}/src/lstrlib.c')"
	system "crtcmod module(lua/ltable) srcstmf('${BASE_DIR}/src/ltable.c')"
	system "crtcmod module(lua/ltablib) srcstmf('${BASE_DIR}/src/ltablib.c')"
	system "crtcmod module(lua/ltm) srcstmf('${BASE_DIR}/src/ltm.c')"
	system "crtcmod module(lua/luam) srcstmf('${BASE_DIR}/src/lua.c')"
	system "crtcmod module(lua/lundump) srcstmf('${BASE_DIR}/src/lundump.c')"
	system "crtcmod module(lua/lutf8lib) srcstmf('${BASE_DIR}/src/lutf8lib.c')"
	system "crtcmod module(lua/lvm) srcstmf('${BASE_DIR}/src/lvm.c')"
	system "crtcmod module(lua/lzio) srcstmf('${BASE_DIR}/src/lzio.c')"
	system "crtpgm pgm(lua/lua) module(lua/lapi lua/lauxlib lua/lbaselib lua/lbitlib lua/lcode lua/lcorolib lua/lctype lua/ldblib lua/ldebug lua/ldo lua/ldump lua/lfunc lua/lgc lua/linit lua/liolib lua/llex lua/lmathlib lua/lmem lua/lmidrange lua/loadlib lua/lobject lua/lopcodes lua/loslib lua/lparser lua/lstate lua/lstring lua/lstrlib lua/ltable lua/ltablib lua/ltm lua/luam lua/lundump lua/lutf8lib lua/lvm lua/lzio)"
